image: node:8.11.4

before_script:
  - yarn

test:
  script:
    - yarn run test:int
    - yarn run test:unit
    - yarn run test:screen

build:
  only:
    - master
    - release
    - hotfix
    - develop
  script:
    - yarn run test:func
