// flow-typed signature: a5926e0c0aaed3dc4abc9feae245efbd
// flow-typed version: <<STUB>>/@feathersjs/authentication-client_v^1.0.9/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@feathersjs/authentication-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@feathersjs/authentication-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@feathersjs/authentication-client/lib/hooks/index' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-client/lib/hooks/populate-access-token' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-client/lib/hooks/populate-entity' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-client/lib/hooks/populate-header' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-client/lib/index' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-client/lib/passport' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-client/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@feathersjs/authentication-client/lib/hooks/index.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-client/lib/hooks/index'>;
}
declare module '@feathersjs/authentication-client/lib/hooks/populate-access-token.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-client/lib/hooks/populate-access-token'>;
}
declare module '@feathersjs/authentication-client/lib/hooks/populate-entity.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-client/lib/hooks/populate-entity'>;
}
declare module '@feathersjs/authentication-client/lib/hooks/populate-header.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-client/lib/hooks/populate-header'>;
}
declare module '@feathersjs/authentication-client/lib/index.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-client/lib/index'>;
}
declare module '@feathersjs/authentication-client/lib/passport.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-client/lib/passport'>;
}
declare module '@feathersjs/authentication-client/lib/utils.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-client/lib/utils'>;
}
