// flow-typed signature: e129dd559684735db4703495deb6e25b
// flow-typed version: <<STUB>>/@feathersjs/feathers_v^3.3.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@feathersjs/feathers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@feathersjs/feathers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@feathersjs/feathers/lib/application' {
  declare module.exports: any;
}

declare module '@feathersjs/feathers/lib/events' {
  declare module.exports: any;
}

declare module '@feathersjs/feathers/lib/hooks/base' {
  declare module.exports: any;
}

declare module '@feathersjs/feathers/lib/hooks/index' {
  declare module.exports: any;
}

declare module '@feathersjs/feathers/lib/index' {
  declare module.exports: any;
}

declare module '@feathersjs/feathers/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@feathersjs/feathers/lib/application.js' {
  declare module.exports: $Exports<'@feathersjs/feathers/lib/application'>;
}
declare module '@feathersjs/feathers/lib/events.js' {
  declare module.exports: $Exports<'@feathersjs/feathers/lib/events'>;
}
declare module '@feathersjs/feathers/lib/hooks/base.js' {
  declare module.exports: $Exports<'@feathersjs/feathers/lib/hooks/base'>;
}
declare module '@feathersjs/feathers/lib/hooks/index.js' {
  declare module.exports: $Exports<'@feathersjs/feathers/lib/hooks/index'>;
}
declare module '@feathersjs/feathers/lib/index.js' {
  declare module.exports: $Exports<'@feathersjs/feathers/lib/index'>;
}
declare module '@feathersjs/feathers/lib/version.js' {
  declare module.exports: $Exports<'@feathersjs/feathers/lib/version'>;
}
