// flow-typed signature: d5bcc7011774e57772c6804b7e1cddbc
// flow-typed version: <<STUB>>/@feathersjs/rest-client_v^1.4.6/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@feathersjs/rest-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@feathersjs/rest-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@feathersjs/rest-client/lib/angular-http-client' {
  declare module.exports: any;
}

declare module '@feathersjs/rest-client/lib/angular' {
  declare module.exports: any;
}

declare module '@feathersjs/rest-client/lib/axios' {
  declare module.exports: any;
}

declare module '@feathersjs/rest-client/lib/base' {
  declare module.exports: any;
}

declare module '@feathersjs/rest-client/lib/fetch' {
  declare module.exports: any;
}

declare module '@feathersjs/rest-client/lib/index' {
  declare module.exports: any;
}

declare module '@feathersjs/rest-client/lib/jquery' {
  declare module.exports: any;
}

declare module '@feathersjs/rest-client/lib/request' {
  declare module.exports: any;
}

declare module '@feathersjs/rest-client/lib/superagent' {
  declare module.exports: any;
}

// Filename aliases
declare module '@feathersjs/rest-client/lib/angular-http-client.js' {
  declare module.exports: $Exports<'@feathersjs/rest-client/lib/angular-http-client'>;
}
declare module '@feathersjs/rest-client/lib/angular.js' {
  declare module.exports: $Exports<'@feathersjs/rest-client/lib/angular'>;
}
declare module '@feathersjs/rest-client/lib/axios.js' {
  declare module.exports: $Exports<'@feathersjs/rest-client/lib/axios'>;
}
declare module '@feathersjs/rest-client/lib/base.js' {
  declare module.exports: $Exports<'@feathersjs/rest-client/lib/base'>;
}
declare module '@feathersjs/rest-client/lib/fetch.js' {
  declare module.exports: $Exports<'@feathersjs/rest-client/lib/fetch'>;
}
declare module '@feathersjs/rest-client/lib/index.js' {
  declare module.exports: $Exports<'@feathersjs/rest-client/lib/index'>;
}
declare module '@feathersjs/rest-client/lib/jquery.js' {
  declare module.exports: $Exports<'@feathersjs/rest-client/lib/jquery'>;
}
declare module '@feathersjs/rest-client/lib/request.js' {
  declare module.exports: $Exports<'@feathersjs/rest-client/lib/request'>;
}
declare module '@feathersjs/rest-client/lib/superagent.js' {
  declare module.exports: $Exports<'@feathersjs/rest-client/lib/superagent'>;
}
